import { useEffect, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { PageFrame } from "@/components/PageFrame";
import AmbientBackground from "@/components/AmbientBackground";
import { useNavigate } from "react-router-dom";
import { Clock, Scissors } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

interface PublicDemo {
  id: string;
  prompt: string;
  selected_tools: string[];
  created_at: string;
  account_model: string;
}

export default function Marketplace() {
  const navigate = useNavigate();
  const [demos, setDemos] = useState<PublicDemo[]>([]);

  useEffect(() => {
    supabase
      .from("experiments")
      .select("id, prompt, selected_tools, created_at, account_model")
      .eq("is_public", true)
      .order("created_at", { ascending: false })
      .limit(20)
      .then(({ data }) => {
        if (data) setDemos(data);
      });
  }, []);

  const handleRemix = (demo: PublicDemo, e: React.MouseEvent) => {
    e.stopPropagation();
    const params = new URLSearchParams();
    params.set("prompt", demo.prompt);
    params.set("tools", demo.selected_tools.join(","));
    navigate(`/?${params.toString()}`);
  };

  return (
    <div className="min-h-screen">
      <AmbientBackground />
      <PageFrame experiment={null} onBack={() => navigate("/")} onVisibilityChange={() => {}}>
        <div className="max-w-6xl mx-auto px-4 py-10">
          <div className="mb-12 text-center">
            <h1 className="text-4xl sm:text-5xl font-serif font-bold tracking-tight mb-4">Community Demos</h1>
            <p className="text-muted-foreground font-sans max-w-xl mx-auto text-base sm:text-lg">
              Explore open demos generated by the community via Phantom Sessions. Find inspiration and remix them with your own ideas.
            </p>
          </div>

          <div className="columns-1 sm:columns-2 lg:columns-3 gap-6 space-y-6">
            {demos.map(demo => (
              <div 
                key={demo.id} 
                className="break-inside-avoid glass-card rounded-2xl overflow-hidden hover:scale-[1.01] transition-transform duration-300 border border-border/50 group cursor-pointer"
                onClick={() => navigate(`/experiment/${demo.id}`)}
              >
                <div className="aspect-video bg-muted/20 relative flex items-center justify-center p-6 border-b border-border/50 overflow-hidden" 
                  style={{
                    backgroundImage: "radial-gradient(circle at 1px 1px, hsl(var(--foreground)/0.1) 1px, transparent 0)",
                    backgroundSize: "16px 16px"
                  }}
                >
                  <div className="relative z-10 w-full p-4 rounded-xl shadow-md border border-border/60 bg-background/90 backdrop-blur-xl">
                    <p className="text-sm font-sans font-medium line-clamp-4 leading-relaxed text-foreground/90">{demo.prompt}</p>
                  </div>
                </div>
                <div className="p-5">
                  <div className="flex flex-wrap gap-1.5 mb-4">
                    {demo.selected_tools.slice(0, 3).map(tool => (
                      <Badge key={tool} variant="secondary" className="text-[9px] font-sans">
                        {tool}
                      </Badge>
                    ))}
                    {demo.selected_tools.length > 3 && (
                      <Badge variant="outline" className="text-[9px] bg-muted/10">
                        +{demo.selected_tools.length - 3}
                      </Badge>
                    )}
                  </div>
                  
                  <div className="flex items-center justify-between mt-6">
                    <div className="flex items-center gap-1.5 text-[10px] text-muted-foreground font-mono">
                      <Clock className="w-3 h-3" />
                      {new Date(demo.created_at).toLocaleDateString()}
                    </div>
                    
                    <Button size="sm" onClick={(e) => handleRemix(demo, e)} className="h-7 text-xs rounded-full bg-foreground text-background hover:bg-foreground/90 font-medium px-4 flex items-center gap-1.5">
                      <Scissors className="w-3 h-3" />
                      Remix this
                    </Button>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </PageFrame>
    </div>
  );
}
