export interface BuilderTool {
  id: string;
  name: string;
  logoUrl: string;
  featured: boolean;
  strengths: string[];
  description: string;
  mockDelayRange: [number, number]; // seconds
  stack: string;
  hosting: string;
  pricing: string;
  category: string;
  referralUrl?: string;
  /** Overlay from `builder_integration_config` when catalog is merged (POP onboarding). */
  integrationEnabled?: boolean;
  integrationTier?: number;
  circuitState?: string;
  circuitOpenedAt?: string | null;
  integrationType?: string | null;
}

export const BUILDER_TOOLS: BuilderTool[] = [
  {
    id: "lovable",
    name: "Lovable",
    logoUrl: "https://lovable.dev/favicon.ico",
    featured: true,
    strengths: ["Full-stack generation", "Supabase integration", "Live preview", "One-click deploy"],
    description: "AI-powered full-stack web app builder with instant preview and deployment.",
    mockDelayRange: [8, 18],
    stack: "React + TypeScript + Tailwind + Supabase",
    hosting: "Lovable Cloud (auto-scaling)",
    pricing: "Free tier + $20/mo Pro",
    category: "Full-stack builder",
  },
  {
    id: "replit",
    name: "Replit",
    logoUrl: "https://www.google.com/s2/favicons?domain=replit.com&sz=64",
    featured: false,
    strengths: ["Multi-language", "Collaborative IDE", "Always-on hosting"],
    description: "Cloud IDE with AI agent for building and deploying apps.",
    mockDelayRange: [12, 25],
    stack: "Node.js + Express + SQLite",
    hosting: "Replit Deployments",
    pricing: "Free tier + $25/mo Hacker",
    category: "Cloud IDE",
  },
  {
    id: "v0",
    name: "Vercel v0",
    logoUrl: "https://www.google.com/s2/favicons?domain=v0.dev&sz=64",
    featured: false,
    strengths: ["UI components", "shadcn/ui native", "Quick iteration"],
    description: "AI-powered UI generation by Vercel, optimized for React components.",
    mockDelayRange: [5, 12],
    stack: "Next.js + TypeScript + Tailwind",
    hosting: "Vercel Edge Network",
    pricing: "Free tier + $20/mo Premium",
    category: "UI generator",
  },
  {
    id: "cursor",
    name: "Cursor",
    logoUrl: "https://www.google.com/s2/favicons?domain=cursor.sh&sz=64",
    featured: false,
    strengths: ["Code-level control", "Multi-file editing", "Git integration"],
    description: "AI-powered code editor for professional developers.",
    mockDelayRange: [15, 30],
    stack: "Any (user-defined)",
    hosting: "Self-hosted",
    pricing: "Free tier + $20/mo Pro",
    category: "Code editor",
  },
  {
    id: "bolt",
    name: "Bolt.new",
    logoUrl: "https://www.google.com/s2/favicons?domain=bolt.new&sz=64",
    featured: false,
    strengths: ["In-browser dev", "WebContainer", "Full-stack"],
    description: "AI-powered full-stack development environment in the browser.",
    mockDelayRange: [7, 16],
    stack: "Any (WebContainer)",
    hosting: "Bolt Cloud",
    pricing: "Free tier + $20/mo Pro",
    category: "In-browser IDE",
  },
  {
    id: "windsurf",
    name: "Windsurf",
    logoUrl: "https://www.google.com/s2/favicons?domain=windsurf.com&sz=64",
    featured: false,
    strengths: ["Agentic IDE", "Cascade flows", "Deep codebase awareness"],
    description: "AI-native IDE by Codeium with agentic Cascade workflows.",
    mockDelayRange: [10, 22],
    stack: "Any (user-defined)",
    hosting: "Self-hosted",
    pricing: "Free tier + $15/mo Pro",
    category: "Code editor",
  },
  {
    id: "github-copilot",
    name: "GitHub Copilot",
    logoUrl: "https://www.google.com/s2/favicons?domain=github.com&sz=64",
    featured: false,
    strengths: ["Code completion", "GitHub integration", "Multi-language"],
    description: "AI pair programmer integrated directly into VS Code and GitHub.",
    mockDelayRange: [8, 18],
    stack: "Any (user-defined)",
    hosting: "Self-hosted",
    pricing: "Free tier + $10/mo Individual",
    category: "Code assistant",
  },
  {
    id: "claude-code",
    name: "Claude Code",
    logoUrl: "https://www.google.com/s2/favicons?domain=anthropic.com&sz=64",
    featured: false,
    strengths: ["Terminal-native", "Large context", "Multi-file edits"],
    description: "Anthropic's agentic coding tool that lives in your terminal.",
    mockDelayRange: [12, 24],
    stack: "Any (user-defined)",
    hosting: "Self-hosted",
    pricing: "Usage-based (API credits)",
    category: "Code agent",
  },
  {
    id: "devin",
    name: "Devin",
    logoUrl: "https://www.google.com/s2/favicons?domain=devin.ai&sz=64",
    featured: false,
    strengths: ["Autonomous agent", "Full environment", "Task planning"],
    description: "Autonomous AI software engineer that can plan, code, and deploy.",
    mockDelayRange: [20, 40],
    stack: "Any (autonomous)",
    hosting: "Devin Cloud",
    pricing: "$500/mo",
    category: "Autonomous agent",
  },
  {
    id: "base44",
    name: "Base44",
    logoUrl: "https://www.google.com/s2/favicons?domain=base44.com&sz=64",
    featured: false,
    strengths: ["Business apps", "Database-first", "No-code friendly"],
    description: "AI app builder focused on business applications and databases.",
    mockDelayRange: [10, 22],
    stack: "React + Python + PostgreSQL",
    hosting: "Base44 Cloud",
    pricing: "Free tier + $29/mo",
    category: "Business app builder",
  },
  {
    id: "tempo",
    name: "Tempo Labs",
    logoUrl: "https://www.google.com/s2/favicons?domain=tempo.new&sz=64",
    featured: false,
    strengths: ["Visual editor", "React-native", "Design-to-code"],
    description: "AI-powered React app builder with visual editing capabilities.",
    mockDelayRange: [8, 18],
    stack: "React + TypeScript + Tailwind",
    hosting: "Tempo Cloud",
    pricing: "Free tier + $20/mo Pro",
    category: "Full-stack builder",
  },
  {
    id: "a0",
    name: "a0.dev",
    logoUrl: "https://www.google.com/s2/favicons?domain=a0.dev&sz=64",
    featured: false,
    strengths: ["Mobile-first", "React Native", "Expo integration"],
    description: "AI app builder specializing in React Native mobile applications.",
    mockDelayRange: [10, 20],
    stack: "React Native + Expo",
    hosting: "Expo / Self-deploy",
    pricing: "Free tier + $20/mo",
    category: "Mobile builder",
  },
  {
    id: "dora",
    name: "Dora AI",
    logoUrl: "https://www.google.com/s2/favicons?domain=dora.run&sz=64",
    featured: false,
    strengths: ["3D websites", "No-code", "Animation-rich"],
    description: "AI website builder with stunning 3D animations and no-code editing.",
    mockDelayRange: [8, 16],
    stack: "Dora Engine (WebGL)",
    hosting: "Dora CDN",
    pricing: "Free tier + $12/mo",
    category: "Website builder",
  },
  {
    id: "pythagora",
    name: "Pythagora / GPT Pilot",
    logoUrl: "https://www.google.com/s2/favicons?domain=pythagora.ai&sz=64",
    featured: false,
    strengths: ["Full-stack agent", "Step-by-step", "Human-in-the-loop"],
    description: "AI dev agent that builds apps step by step with developer oversight.",
    mockDelayRange: [15, 30],
    stack: "Node.js + React + PostgreSQL",
    hosting: "Self-hosted",
    pricing: "Free (open source)",
    category: "Code agent",
  },
  {
    id: "create-xyz",
    name: "Create.xyz",
    logoUrl: "https://www.google.com/s2/favicons?domain=create.xyz&sz=64",
    featured: false,
    strengths: ["Prompt-to-app", "AI integration", "Rapid prototyping"],
    description: "Turn text descriptions into functional web apps with AI features built in.",
    mockDelayRange: [6, 14],
    stack: "React + Node.js",
    hosting: "Create Cloud",
    pricing: "Free tier + $19/mo",
    category: "Full-stack builder",
  },
  {
    id: "softgen",
    name: "Softgen",
    logoUrl: "https://www.google.com/s2/favicons?domain=softgen.ai&sz=64",
    featured: false,
    strengths: ["Firebase-native", "Full-stack", "Live preview"],
    description: "AI full-stack builder with Firebase backend and instant deployments.",
    mockDelayRange: [8, 18],
    stack: "React + Firebase",
    hosting: "Firebase Hosting",
    pricing: "Free tier + $29/mo",
    category: "Full-stack builder",
  },
  {
    id: "aider",
    name: "Aider",
    logoUrl: "https://www.google.com/s2/favicons?domain=aider.chat&sz=64",
    featured: false,
    strengths: ["Terminal-based", "Git-aware", "Multi-model"],
    description: "Open-source AI pair programming tool that works in your terminal with git.",
    mockDelayRange: [10, 22],
    stack: "Any (user-defined)",
    hosting: "Self-hosted",
    pricing: "Free (open source)",
    category: "Code assistant",
  },
  {
    id: "cody",
    name: "Sourcegraph Cody",
    logoUrl: "https://www.google.com/s2/favicons?domain=sourcegraph.com&sz=64",
    featured: false,
    strengths: ["Codebase context", "Multi-repo", "Enterprise"],
    description: "AI coding assistant with deep codebase understanding by Sourcegraph.",
    mockDelayRange: [8, 16],
    stack: "Any (user-defined)",
    hosting: "Self-hosted / Cloud",
    pricing: "Free tier + $9/mo Pro",
    category: "Code assistant",
  },
  {
    id: "gemini-code",
    name: "Gemini Code Assist",
    logoUrl: "https://www.google.com/s2/favicons?domain=cloud.google.com&sz=64",
    featured: false,
    strengths: ["Google Cloud", "Large context", "Multi-language"],
    description: "Google's AI coding assistant powered by Gemini models.",
    mockDelayRange: [8, 18],
    stack: "Any (user-defined)",
    hosting: "Self-hosted",
    pricing: "Free tier + usage-based",
    category: "Code assistant",
  },
  {
    id: "amazon-q",
    name: "Amazon Q Developer",
    logoUrl: "https://www.google.com/s2/favicons?domain=aws.amazon.com&sz=64",
    featured: false,
    strengths: ["AWS integration", "Security scans", "Code transformation"],
    description: "Amazon's AI assistant for software development and AWS operations.",
    mockDelayRange: [10, 22],
    stack: "Any (AWS-optimized)",
    hosting: "AWS",
    pricing: "Free tier + $19/mo Pro",
    category: "Code assistant",
  },
  {
    id: "antigravity",
    name: "Antigravity",
    logoUrl: "https://www.google.com/s2/favicons?domain=antigravity.dev&sz=64",
    featured: false,
    strengths: ["Rapid prototyping", "Design-to-code", "Mobile-first"],
    description: "AI design-to-code platform for rapid prototyping.",
    mockDelayRange: [8, 20],
    stack: "React Native + TypeScript",
    hosting: "Antigravity Cloud",
    pricing: "Free beta",
    category: "Mobile builder",
  },
  {
    id: "build0",
    name: "Build0",
    logoUrl: "https://www.google.com/s2/favicons?domain=build0.dev&sz=64",
    featured: false,
    strengths: ["Zero-config", "Instant deploy", "Template library"],
    description: "Zero-configuration AI app builder with instant deployments.",
    mockDelayRange: [6, 15],
    stack: "Next.js + Prisma + PostgreSQL",
    hosting: "Build0 Infrastructure",
    pricing: "Free tier + $15/mo",
    category: "Full-stack builder",
  },
  {
    id: "orchids",
    name: "Orchids",
    logoUrl: "https://www.google.com/s2/favicons?domain=orchids.dev&sz=64",
    featured: false,
    strengths: ["Beautiful UI", "Animation-rich", "Design systems"],
    description: "AI builder focused on beautiful, animation-rich interfaces.",
    mockDelayRange: [10, 24],
    stack: "React + Framer Motion + Tailwind",
    hosting: "Orchids CDN",
    pricing: "Free tier + $19/mo",
    category: "Design-focused builder",
  },
  {
    id: "floot",
    name: "Floot",
    logoUrl: "https://www.google.com/s2/favicons?domain=floot.ai&sz=64",
    featured: false,
    strengths: ["API integration", "Workflow automation", "Enterprise ready"],
    description: "Enterprise-grade AI app builder with workflow automation.",
    mockDelayRange: [14, 28],
    stack: "Next.js + tRPC + PostgreSQL",
    hosting: "AWS (managed)",
    pricing: "From $49/mo",
    category: "Enterprise builder",
  },
  {
    id: "tabnine",
    name: "Tabnine",
    logoUrl: "https://www.google.com/s2/favicons?domain=tabnine.com&sz=64",
    featured: false,
    strengths: ["Privacy-focused", "On-premise", "Code completion"],
    description: "AI code assistant with privacy-first approach and on-premise options.",
    mockDelayRange: [6, 14],
    stack: "Any (user-defined)",
    hosting: "Self-hosted / Cloud",
    pricing: "Free tier + $12/mo Pro",
    category: "Code assistant",
  },
];

export const getToolById = (id: string) => BUILDER_TOOLS.find((t) => t.id === id);
