INSERT INTO builder_pricing_plans (tool_id, plan_name, monthly_price, annual_price, credits_included, credit_unit, overage_cost, ai_models, dev_environment, features) VALUES
('lovable', 'free', 0, 0, 5, 'messages', NULL, ARRAY['Claude 3.5 Sonnet', 'GPT-4o'], 'Browser IDE', '["Live preview","Supabase integration","One-click deploy"]'::jsonb),
('lovable', 'pro', 20, 192, 500, 'messages', 0.10, ARRAY['Claude 3.5 Sonnet', 'GPT-4o'], 'Browser IDE', '["Live preview","Supabase integration","One-click deploy","Custom domains","Priority support"]'::jsonb),
('lovable', 'team', 50, 480, 2000, 'messages', 0.08, ARRAY['Claude 3.5 Sonnet', 'GPT-4o'], 'Browser IDE', '["Live preview","Supabase integration","One-click deploy","Custom domains","Priority support","Team collaboration"]'::jsonb),
('replit', 'free', 0, 0, 0, 'repls', NULL, ARRAY['Replit AI'], 'Cloud IDE', '["Multi-language","Multiplayer","Community"]'::jsonb),
('replit', 'pro', 25, 240, 0, 'power-ups', NULL, ARRAY['Replit AI', 'GPT-4'], 'Cloud IDE', '["Multi-language","Multiplayer","Always-on hosting","Boosted compute"]'::jsonb),
('v0', 'free', 0, 0, 200, 'generations', NULL, ARRAY['Claude 3.5 Sonnet'], 'Browser', '["UI generation","shadcn/ui","Component export"]'::jsonb),
('v0', 'pro', 20, 192, 5000, 'generations', 0.01, ARRAY['Claude 3.5 Sonnet', 'GPT-4o'], 'Browser', '["UI generation","shadcn/ui","Component export","Private projects","Priority queue"]'::jsonb),
('cursor', 'free', 0, 0, 50, 'slow-requests', NULL, ARRAY['GPT-3.5'], 'VS Code Fork', '["Code completion","Multi-file editing","Chat"]'::jsonb),
('cursor', 'pro', 20, 192, 500, 'fast-requests', 0.04, ARRAY['Claude 3.5 Sonnet', 'GPT-4o', 'GPT-4'], 'VS Code Fork', '["Code completion","Multi-file editing","Chat","Composer","Unlimited slow requests"]'::jsonb),
('base44', 'free', 0, 0, 10, 'generations', NULL, ARRAY['GPT-4o'], 'Browser IDE', '["Database-first","Business apps","No-code friendly"]'::jsonb),
('base44', 'pro', 29, 278, 200, 'generations', 0.15, ARRAY['GPT-4o'], 'Browser IDE', '["Database-first","Business apps","No-code friendly","Custom domains","API access"]'::jsonb),
('antigravity', 'free', 0, 0, 5, 'projects', NULL, ARRAY['Claude 3.5 Sonnet'], 'Browser', '["Design-to-code","Mobile-first","Rapid prototyping"]'::jsonb),
('build0', 'free', 0, 0, 3, 'projects', NULL, ARRAY['GPT-4o'], 'Browser IDE', '["Zero-config","Instant deploy","Template library"]'::jsonb),
('build0', 'pro', 15, 144, 50, 'projects', 0.50, ARRAY['GPT-4o', 'Claude 3.5 Sonnet'], 'Browser IDE', '["Zero-config","Instant deploy","Template library","Custom domains","Priority queue"]'::jsonb),
('orchids', 'free', 0, 0, 5, 'generations', NULL, ARRAY['GPT-4o'], 'Browser', '["Beautiful UI","Animation-rich","Design systems"]'::jsonb),
('orchids', 'pro', 19, 180, 100, 'generations', 0.20, ARRAY['GPT-4o', 'Claude 3.5 Sonnet'], 'Browser', '["Beautiful UI","Animation-rich","Design systems","Export code","Custom branding"]'::jsonb),
('floot', 'pro', 49, 468, 500, 'generations', 0.10, ARRAY['GPT-4o', 'Claude 3.5 Sonnet'], 'Cloud IDE', '["API integration","Workflow automation","Enterprise SSO","Team management"]'::jsonb),
('floot', 'enterprise', 149, 1428, 5000, 'generations', 0.05, ARRAY['GPT-4o', 'Claude 3.5 Sonnet', 'GPT-4'], 'Cloud IDE', '["API integration","Workflow automation","Enterprise SSO","Team management","SLA","Dedicated support"]'::jsonb),
('bolt', 'free', 0, 0, 0, 'tokens', NULL, ARRAY['Claude 3.5 Sonnet'], 'WebContainer', '["In-browser dev","Full-stack","npm support"]'::jsonb),
('bolt', 'pro', 20, 192, 10000000, 'tokens', NULL, ARRAY['Claude 3.5 Sonnet', 'GPT-4o'], 'WebContainer', '["In-browser dev","Full-stack","npm support","Unlimited projects","Deploy to Netlify"]'::jsonb)
ON CONFLICT (tool_id, plan_name) DO UPDATE SET
  monthly_price = EXCLUDED.monthly_price,
  annual_price = EXCLUDED.annual_price,
  credits_included = EXCLUDED.credits_included,
  credit_unit = EXCLUDED.credit_unit,
  overage_cost = EXCLUDED.overage_cost,
  ai_models = EXCLUDED.ai_models,
  dev_environment = EXCLUDED.dev_environment,
  features = EXCLUDED.features,
  updated_at = now();